language: ruby

install: echo "party time"

script: echo "like it is cat meow 99" && true

before_deploy:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip

deploy:
  provider: s3
  access_key_id: AKIAIHC76JF3TVQIDUBQ
  secret_access_key: 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
  bucket: vishnutravisdemo
