language: ruby

install: echo "party time"

script: echo "like it is cat meow 99" && true

before_deploy:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip

deploy:
  provider: s3
  access_key_id: AKIAIATCRF6B3TPGVN5Q
  secret_access_key: 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
  bucket: vishnutravisdemo
